-- Add missing columns to users table that are required by the backend

ALTER TABLE users ADD COLUMN IF NOT EXISTS role TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS college TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS grad_year TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS location TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS github_url TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS linkedin_url TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS resume_url TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS resume_name TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS resume_uploaded_at TIMESTAMP;
ALTER TABLE users ADD COLUMN IF NOT EXISTS resume_score INTEGER DEFAULT 0;
